# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2be40542836e8b91f0f4c244dd711e13dd0ce1decf4e2e0ca0d1ae7a8bc2edf232a5ee9246238fa5c4eb9621550042bbe3f5d9dc90404a7577c6096a38b02af3

test:
  secret_key_base: 3c4845a1d4d0d07870862e9b3eeae3ef0948b8ebad1eb164f3f83e4f5c94dbf4439ff9e4bc9f4c937a820300842ca069a803d130c011bd88815289a07c4b151f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
